<?php
$jenis = ($_GET['jenis'] ?? 'himpunan') === 'ukm' ? 'ukm' : 'himpunan';
$page_title = $jenis === 'ukm' ? 'Detail UKM' : 'Detail Himpunan Mahasiswa';
require_once __DIR__ . '/../../config/auth.php'; wajib_login();
$slug=trim($_GET['slug']??'');
$st=$pdo->prepare('SELECT * FROM kemahasiswaan_organisasi WHERE slug=? AND jenis=? LIMIT 1'); $st->execute([$slug,$jenis]); $org=$st->fetch();
if(!$org){http_response_code(404); die('Organisasi tidak ditemukan.');}
$dirs=['pengurus'=>'../../uploads/kemahasiswaan/pengurus/','anggota'=>'../../uploads/kemahasiswaan/anggota/','kegiatan'=>'../../uploads/kemahasiswaan/kegiatan/','galeri'=>'../../uploads/kemahasiswaan/galeri/'];
foreach($dirs as $k=>$u){$p=__DIR__.'/../../uploads/kemahasiswaan/'.$k.'/';if(!is_dir($p))@mkdir($p,0777,true);}
function dm_upload($field,$dir,$old=''){ if(empty($_FILES[$field]['name']))return $old; $allowed=['jpg','jpeg','png','webp','svg'];$ext=strtolower(pathinfo($_FILES[$field]['name'],PATHINFO_EXTENSION));if(!in_array($ext,$allowed,true)||$_FILES[$field]['size']>4*1024*1024)return $old;$name='km_'.date('YmdHis').'_'.bin2hex(random_bytes(3)).'.'.$ext;$abs=__DIR__.'/../../uploads/kemahasiswaan/'.$dir.'/'.$name;if(move_uploaded_file($_FILES[$field]['tmp_name'],$abs)){if($old&&is_file(__DIR__.'/../../uploads/kemahasiswaan/'.$dir.'/'.basename($old)))@unlink(__DIR__.'/../../uploads/kemahasiswaan/'.$dir.'/'.basename($old));return $name;}return $old;}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $a=$_POST['action']??'';$id=(int)($_POST['id']??0);
  try{
    if($a==='save_pengurus'){ $foto=dm_upload('foto','pengurus',$_POST['old_foto']??'');$d=[trim($_POST['nama']??''),trim($_POST['jabatan']??''),$foto,max(1,(int)($_POST['nomor_urut']??1)),($_POST['status']??'aktif')==='nonaktif'?'nonaktif':'aktif']; if($id)$pdo->prepare('UPDATE kemahasiswaan_pengurus SET nama=?,jabatan=?,foto=?,nomor_urut=?,status=? WHERE id=? AND organisasi_slug=?')->execute([...$d,$id,$slug]);else$pdo->prepare('INSERT INTO kemahasiswaan_pengurus(nama,jabatan,foto,nomor_urut,status,organisasi_slug) VALUES(?,?,?,?,?,?)')->execute([...$d,$slug]); }
    elseif($a==='save_anggota'){ $foto=dm_upload('foto','anggota',$_POST['old_foto']??'');$d=[trim($_POST['nama']??''),trim($_POST['nim']??''),trim($_POST['prodi']??''),trim($_POST['angkatan']??''),trim($_POST['jabatan']??''),$foto,($_POST['status']??'aktif')==='nonaktif'?'nonaktif':'aktif']; if($id)$pdo->prepare('UPDATE kemahasiswaan_anggota SET nama=?,nim=?,prodi=?,angkatan=?,jabatan=?,foto=?,status=? WHERE id=? AND organisasi_slug=?')->execute([...$d,$id,$slug]);else$pdo->prepare('INSERT INTO kemahasiswaan_anggota(nama,nim,prodi,angkatan,jabatan,foto,status,organisasi_slug) VALUES(?,?,?,?,?,?,?,?)')->execute([...$d,$slug]); }
    elseif($a==='save_kegiatan'){ $foto=dm_upload('foto','kegiatan',$_POST['old_foto']??'');$d=[trim($_POST['judul']??''),($_POST['tanggal_kegiatan']??'')?:null,trim($_POST['deskripsi']??''),$foto,max(1,(int)($_POST['nomor_urut']??1)),($_POST['status']??'publish')==='draft'?'draft':'publish']; if($id)$pdo->prepare('UPDATE kemahasiswaan_kegiatan SET judul=?,tanggal_kegiatan=?,deskripsi=?,foto=?,nomor_urut=?,status=? WHERE id=? AND organisasi_slug=?')->execute([...$d,$id,$slug]);else$pdo->prepare('INSERT INTO kemahasiswaan_kegiatan(judul,tanggal_kegiatan,deskripsi,foto,nomor_urut,status,organisasi_slug) VALUES(?,?,?,?,?,?,?)')->execute([...$d,$slug]); }
    elseif($a==='save_galeri'){ $foto=dm_upload('foto','galeri',$_POST['old_foto']??'');if(!$foto)throw new RuntimeException('Foto galeri wajib diunggah.');$d=[trim($_POST['judul']??''),$foto,trim($_POST['keterangan']??''),max(1,(int)($_POST['nomor_urut']??1)),($_POST['status']??'publish')==='draft'?'draft':'publish'];if($id)$pdo->prepare('UPDATE kemahasiswaan_galeri SET judul=?,foto=?,keterangan=?,nomor_urut=?,status=? WHERE id=? AND organisasi_slug=?')->execute([...$d,$id,$slug]);else$pdo->prepare('INSERT INTO kemahasiswaan_galeri(judul,foto,keterangan,nomor_urut,status,organisasi_slug) VALUES(?,?,?,?,?,?)')->execute([...$d,$slug]); }
    elseif($a==='delete'){ $map=['pengurus'=>'kemahasiswaan_pengurus','anggota'=>'kemahasiswaan_anggota','kegiatan'=>'kemahasiswaan_kegiatan','galeri'=>'kemahasiswaan_galeri'];$t=$map[$_POST['tab']??'']??'';if($t){$pdo->prepare("DELETE FROM $t WHERE id=? AND organisasi_slug=?")->execute([$id,$slug]);}}
    header('Location:detail.php?jenis='.$jenis.'&slug='.rawurlencode($slug).'&tab='.rawurlencode($_POST['tab']??'pengurus').'&ok=Data berhasil disimpan.');exit;
  }catch(Throwable $e){header('Location:detail.php?jenis='.$jenis.'&slug='.rawurlencode($slug).'&err='.rawurlencode($e->getMessage()));exit;}
}
$tab=$_GET['tab']??'pengurus'; if(!in_array($tab,['pengurus','anggota','kegiatan','galeri'],true))$tab='pengurus';
$map=['pengurus'=>'kemahasiswaan_pengurus','anggota'=>'kemahasiswaan_anggota','kegiatan'=>'kemahasiswaan_kegiatan','galeri'=>'kemahasiswaan_galeri'];
$rows=$pdo->prepare('SELECT * FROM '.$map[$tab].' WHERE organisasi_slug=? ORDER BY '.($tab==='kegiatan'?'tanggal_kegiatan DESC,nomor_urut,id DESC':($tab==='anggota'?'nama ASC': 'nomor_urut ASC,id DESC')));$rows->execute([$slug]);$rows=$rows->fetchAll();
$editId=(int)($_GET['edit']??0);$edit=[];if($editId){$st=$pdo->prepare('SELECT * FROM '.$map[$tab].' WHERE id=? AND organisasi_slug=?');$st->execute([$editId,$slug]);$edit=$st->fetch()?:[];}
include __DIR__.'/../../includes/header.php';
?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>.kd{padding:24px}.kd-org{display:flex;gap:15px;align-items:center;padding:18px;border:1px solid #e3ebe8;background:#fff;border-radius:16px;margin-bottom:18px}.kd-org img{width:72px;height:72px;object-fit:contain;border-radius:14px;background:#f4f8f6}.kd-org h2{margin:0;color:#173b36}.kd-org p{margin:5px 0 0;color:#6b7d76;font-size:12px}.kd-tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:18px}.kd-tabs a{padding:9px 13px;border:1px solid #dce7e3;border-radius:9px;text-decoration:none;color:#36534a;background:#fff;font-size:12px;font-weight:700}.kd-tabs a.active{background:#087f5b;color:#fff}.kd-grid{display:grid;grid-template-columns:360px 1fr;gap:18px}.kd-card{background:#fff;border:1px solid #e3ebe8;border-radius:16px;padding:18px}.kd-form{display:grid;gap:11px}.kd-form label{font-size:11px;font-weight:700;color:#466158}.kd-form input,.kd-form select,.kd-form textarea{width:100%;box-sizing:border-box;padding:9px 10px;border:1px solid #dce7e3;border-radius:9px;font:inherit}.kd-form textarea{min-height:80px}.kd-btn{display:inline-flex;padding:8px 11px;border-radius:8px;border:0;text-decoration:none;font-size:11px;font-weight:700;background:#eef4f1;color:#27483d;cursor:pointer}.kd-btn.primary{background:#087f5b;color:#fff}.kd-btn.danger{background:#fff0f0;color:#b42318}.kd-table{width:100%;border-collapse:collapse}.kd-table th,.kd-table td{padding:10px;border-bottom:1px solid #edf2f0;text-align:left;font-size:11px}.kd-table th{background:#f8fbfa;color:#587069}.kd-photo{width:48px;height:48px;object-fit:cover;border-radius:8px;background:#f2f6f4}@media(max-width:900px){.kd-grid{grid-template-columns:1fr}}@media(max-width:600px){.kd{padding:14px}.kd-table{min-width:720px}.kd-card.table{overflow:auto}}</style>
<div class="kd"><div class="page-head"><div><span class="eyebrow">KEMAHASISWAAN</span><h1>Kelola Detail</h1><p>Data lengkap organisasi untuk halaman frontend.</p></div><a class="btn" href="index.php?jenis=<?=$jenis?>">← Kembali</a></div>
<div class="kd-org"><?php if($org['logo']):?><img src="../../uploads/kemahasiswaan/logo/<?=rawurlencode(basename($org['logo']))?>" alt="<?=e($org['nama'])?>"><?php endif;?><div><h2><?=e($org['nama'])?></h2><p><?=e($org['kategori']?:ucfirst($jenis))?> · slug: <?=e($org['slug'])?></p></div></div>
<div class="kd-tabs"><?php foreach(['pengurus'=>'Pengurus','anggota'=>'Anggota','kegiatan'=>'Kegiatan','galeri'=>'Galeri Foto'] as $k=>$v):?><a class="<?=$tab===$k?'active':''?>" href="detail.php?jenis=<?=$jenis?>&slug=<?=rawurlencode($slug)?>&tab=<?=$k?>"><?=e($v)?></a><?php endforeach;?></div>
<div class="kd-grid"><div class="kd-card"><h3><?= $edit?'Edit':'Tambah' ?> <?=ucfirst($tab)?></h3><form class="kd-form" method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="save_<?=$tab?>"><input type="hidden" name="tab" value="<?=$tab?>"><input type="hidden" name="id" value="<?=e($edit['id']??0)?>"><input type="hidden" name="old_foto" value="<?=e($edit['foto']??'')?>">
<?php if($tab==='pengurus'):?><label>Nama *</label><input name="nama" required value="<?=e($edit['nama']??'')?>"><label>Jabatan *</label><input name="jabatan" required value="<?=e($edit['jabatan']??'')?>"><label>Urutan</label><input type="number" name="nomor_urut" value="<?=e($edit['nomor_urut']??1)?>"><label>Foto</label><input type="file" name="foto" accept=".jpg,.jpeg,.png,.webp,.svg"><label>Status</label><select name="status"><option value="aktif">Aktif</option><option value="nonaktif" <?=($edit['status']??'')==='nonaktif'?'selected':''?>>Nonaktif</option></select>
<?php elseif($tab==='anggota'):?><label>Nama *</label><input name="nama" required value="<?=e($edit['nama']??'')?>"><label>NIM</label><input name="nim" value="<?=e($edit['nim']??'')?>"><label>Program Studi</label><input name="prodi" value="<?=e($edit['prodi']??'')?>"><label>Angkatan</label><input name="angkatan" value="<?=e($edit['angkatan']??'')?>"><label>Jabatan</label><input name="jabatan" value="<?=e($edit['jabatan']??'')?>"><label>Foto</label><input type="file" name="foto" accept=".jpg,.jpeg,.png,.webp,.svg"><label>Status</label><select name="status"><option value="aktif">Aktif</option><option value="nonaktif" <?=($edit['status']??'')==='nonaktif'?'selected':''?>>Nonaktif</option></select>
<?php elseif($tab==='kegiatan'):?><label>Judul *</label><input name="judul" required value="<?=e($edit['judul']??'')?>"><label>Tanggal</label><input type="date" name="tanggal_kegiatan" value="<?=e($edit['tanggal_kegiatan']??'')?>"><label>Deskripsi</label><textarea name="deskripsi"><?=e($edit['deskripsi']??'')?></textarea><label>Foto</label><input type="file" name="foto" accept=".jpg,.jpeg,.png,.webp,.svg"><label>Urutan</label><input type="number" name="nomor_urut" value="<?=e($edit['nomor_urut']??1)?>"><label>Status</label><select name="status"><option value="publish">Publish</option><option value="draft" <?=($edit['status']??'')==='draft'?'selected':''?>>Draft</option></select>
<?php else: ?><label>Judul *</label><input name="judul" required value="<?=e($edit['judul']??'')?>"><label>Foto *</label><input type="file" name="foto" accept=".jpg,.jpeg,.png,.webp" <?=empty($edit)?'required':''?>><label>Keterangan</label><input name="keterangan" value="<?=e($edit['keterangan']??'')?>"><label>Urutan</label><input type="number" name="nomor_urut" value="<?=e($edit['nomor_urut']??1)?>"><label>Status</label><select name="status"><option value="publish">Publish</option><option value="draft" <?=($edit['status']??'')==='draft'?'selected':''?>>Draft</option></select><?php endif;?><button class="kd-btn primary" type="submit">Simpan</button><?php if($edit):?><a class="kd-btn" href="detail.php?jenis=<?=$jenis?>&slug=<?=rawurlencode($slug)?>&tab=<?=$tab?>">Batal</a><?php endif;?></form></div>
<div class="kd-card table"><h3>Data <?=ucfirst($tab)?></h3><table class="kd-table"><thead><tr><?php if($tab!=='galeri'):?><th>Foto</th><?php endif;?><th>Informasi</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="4">Belum ada data.</td></tr><?php else:foreach($rows as $r):?><tr><?php if($tab!=='galeri'):?><td><?php if(!empty($r['foto'])):?><img class="kd-photo" src="<?=$dirs[$tab]?><?=rawurlencode(basename($r['foto']))?>" alt=""><?php endif;?></td><?php endif;?><td><b><?=e($r['nama']??$r['judul'])?></b><?php if($tab==='pengurus'):?> — <?=e($r['jabatan'])?><?php elseif($tab==='anggota'):?><br><?=e($r['nim']??'')?> · <?=e($r['prodi']??'')?> · <?=e($r['angkatan']??'')?><?php elseif($tab==='kegiatan'):?><br><?=e($r['tanggal_kegiatan']??'')?><?php else:?><br><?=e($r['keterangan']??'')?><?php endif;?></td><td><?=e($r['status'])?></td><td><a class="kd-btn" href="detail.php?jenis=<?=$jenis?>&slug=<?=rawurlencode($slug)?>&tab=<?=$tab?>&edit=<?=$r['id']?>">Edit</a><form style="display:inline" method="post" onsubmit="return confirm('Hapus data ini?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="tab" value="<?=$tab?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="kd-btn danger">Hapus</button></form></td></tr><?php endforeach;endif;?></tbody></table></div></div></div>
<?php if(isset($_GET['ok'])):?><script>Swal.fire({icon:'success',title:'Berhasil',text:<?=json_encode($_GET['ok'])?>,timer:1500,showConfirmButton:false});</script><?php endif;?><?php if(isset($_GET['err'])):?><script>Swal.fire({icon:'error',title:'Gagal',text:<?=json_encode($_GET['err'])?>});</script><?php endif;?>
<?php require __DIR__.'/../../includes/footer.php';?>
